### PR TITLE
vii+/vi -> VII+/ii in n13op130_01.tsv

### LINKED ISSUE #25: Apparent issue in n13op130_01.tsv
In [measure 142 of n13op130_01.tsv](https://github.com/DCMLab/ABC/blob/v2/harmonies/n13op130_01.tsv#L445) the harmony is designated as "#vii+/vi". Here's the measure in question:

Screen Shot 2022-08-03 at 2 13 12 PM
 
The pitch-classes of this harmony are B-natural, E-flat, and G. The annotation seems wrong in at least two ways:
1. The key is B-flat, so vi would be G. Presumably, the secondary roman numeral is meant to be ii (C), not vi (G).
2. Upper case is ordinarily used for augmented chords. I did a grep on all the tsv files in harmonies and this seems to be the only case where a lower-case roman numeral is followed by '+'.

### PR DESCRIPTION
**Pull request by malcolmsailor**
Resolves #25

### CODE REVIEW

**Comment by johentsch** [comment]
Thank you for the PR! I'm closing it because it is now superseded by #27 .

If, in the future, you find more inconsistencies and would like to help us correcting them, we would need you to make the change within the score and to then update the TSV file using our parser. The steps would be:

* install version 0.4.11 of the parser (`pip install ms3==0.4.11`)
* change the label in the MSCX file and store
* update the TSV using the command `ms3 extract -X -f MS3/n13op130_01.mscx`
* commit the changes together and have the commit message begin with the measure number.

PRs in this style (compare #27) will be very much welcomed!

**Comment by malcolmsailor** [comment]
@johentsch, just now I looked into making a pull request in the style you suggested but I noticed that the parser produced a different version of the harmony table (specifically, it was lacking the quarterbeats and duration_qb columns; possibly others as well). Do I perhaps need another (newer?) version of the ms3 parser than 0.4.11?

Also I noticed that my version of MuseScore added a few lines to the mscx file, viz.

```
+        <Channel name="harmony">
+          <controller ctrl="0" value="0"/>
+          <controller ctrl="32" value="17"/>
+          <program value="0"/>
+          <controller ctrl="10" value="63"/>
+          <synti>Fluid</synti>
+          </Channel>
```
Looks like this is something about fluidsynth. Does it matter? Do you know how to avoid that?

**Comment by johentsch** [comment]
Right now, the PR should go into the `v2` branch, i.e. without quarterbeat column. From there, we can always update the `v2_preview` branch. The two columns are added through the parameter `-q` as in `ms3 extract -X -q`.

As for the fluidsynth it looks like a setting for the playback of the Roman Numeral layer. I'm assuming you're also using MuseScore 3.6.2, so probably it's something related to settings? Actually it's irrelevant, I wouldn't mind it, but would be interested to know why it showed up.

**Comment by malcolmsailor** [comment]
OK, I take it there is a reason you don't want to push the quarterbeats to the v2 branch? I'm relying on the quarterbeats column so it'll make it a little more complicated for me to make these changes in my local fork.

I'm not sure why the fluidsynth thing turned up, I noticed it doesn't show up in every file. I'll see if I can work it out.

**Comment by malcolmsailor** [comment]
OK, I think I figured out the fluidsynth thing. Actually, those lines are already present in many but not all of the files; if they are missing, then my MuseScore adds them. It seems to be a channel to playback the harmonies.

For example, here is the instrument entry for the cello in n13op130_02.mscx, with harmony channel defined:
```
      <Instrument id="violoncello">
        <trackName>Cello</trackName>
        <instrumentId>strings.cello</instrumentId>
        <Channel>
          <controller ctrl="0" value="0"/>
          <controller ctrl="32" value="17"/>
          <program value="42"/>
          <controller ctrl="7" value="101"/>
          <controller ctrl="10" value="63"/>
          <synti>Fluid</synti>
          </Channel>
        <Channel name="harmony">
          <controller ctrl="0" value="0"/>
          <controller ctrl="32" value="17"/>
          <program value="0"/>
          <controller ctrl="7" value="101"/>
          <controller ctrl="10" value="63"/>
          <synti>Fluid</synti>
          </Channel>
        </Instrument>
```

And here is the same entry in `n11op95_04.mscx`, with harmony channel missing. My MuseScore adds it when I save the file.
```
      <Instrument id="violoncello">
        <longName>Cello</longName>
        <trackName>Cello</trackName>
        <instrumentId>strings.cello</instrumentId>
        <Channel>
          <controller ctrl="0" value="0"/>
          <controller ctrl="32" value="17"/>
          <program value="42"/>
          <controller ctrl="7" value="109"/>
          <controller ctrl="10" value="63"/>
          <synti>Fluid</synti>
          </Channel>
        </Instrument>
```

There are also some other small changes MuseScore seems to make. I guess these don't matter either? The important changes will show up as differences in the note and chord tables.

**Comment by johentsch** [comment]
> if they are missing, then my MuseScore adds them. It seems to be a channel to playback the harmonies.

Cool, that's what I had guessed, thanks for figuring it out!

**Comment by johentsch** [comment]
> I take it there is a reason you don't want to push the quarterbeats to the v2 branch?

Yes because we expect other changes to the column -- so better to do them all at once. What I can offer is that you create PRs where you change the scores and I take care of updating the TSVs on both branches.

**Pull request closed without merging**
